<TracksList>
        MdFlatButton:
                id: trackButton
                md_bg_color: app.theme_cls.primary_color
        BoxLayout:
                orientation:"horizontal"
                MDFlatButton:
                        text: "Add tones"
                        md_bg_color: app.theme_cls.primary_color

                
        #GetTrackButton:
        #    tracks_grid: tracks_grid